spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url:
server:
  port: 8768

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
info:
  author: zyq
  version: 1.1